# Generated by Django 5.1.1 on 2026-02-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=20)),
                ('priezvisko', models.CharField(max_length=20)),
                ('trieda', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ucitel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titul', models.CharField(max_length=10)),
                ('meno', models.CharField(max_length=20)),
                ('priezvisko', models.CharField(max_length=20)),
            ],
        ),
    ]
