# Generated by Django 5.1.1 on 2025-12-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=100)),
                ('priezvisko', models.CharField(max_length=100)),
                ('vek', models.IntegerField()),
                ('datum', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('muz', models.BooleanField()),
            ],
        ),
    ]
